Heading levels
node-girls/node-girls-website pull request #110
Opened 2018-10-07 20:29 UTC by BNewing

I noticed that the heading levels weren't hierarchical across the site, so this PR goes through all of the pages and updates them. In this PR each page has a h1 and that all following header tags are at the appropriate level.

I did this because screen reader users often use heading levels to navigate the page: https://www.w3.org/WAI/tutorials/page-structure/headings/

In some cases, the heading levels had been used because of the styling that materialize gave them, so I've created a few classes in the CSS file so that the site still looks the same nearly everywhere. I tried to follow other CSS conventions in the project. 

There is one instance where it doesn't match the live site, and screenshots are below. I felt like with the image spacing them out, it looks okay, but happy to change it to the current design on the site if you'd prefer that! (I'm not sure why the icons are appearing on my local site and not the live site)

Contact info for different chapters appears as follows in my PR: ![screen shot 2018-10-07 at 21 17 00](https://user-images.githubusercontent.com/16868713/46586539-d0ee5780-ca77-11e8-80ca-08b54e2f39ca.png)

Icons appearing on top of page for me locally: ![oxford-strapline](https://user-images.githubusercontent.com/16868713/46586531-b5834c80-ca77-11e8-8faa-a218d48f5428.png)

I've gone through and compared it page by page for every page twice on two separate occasions, as I wasn't sure how to test it. In some places, it isn't pixel perfect with margins, but the font-sizes have been kept consistent with the live site :)

2018-10-08 08:26 UTC, minaorangina requested changes
Thanks so much for the PR @BNewing!  I've spotted a couple of small issues and left some comments. Once they're sorted it can be merged 🎉

2018-10-08 08:26 UTC, minaorangina commented on events.html
> +            <div class="titlep
typo: "titlep --> "title"

2018-10-08 08:26 UTC, minaorangina commented on events.html
> +            <div classptitle">
typo: classptitle" --> class="title"

2018-10-08 08:26 UTC, minaorangina commented on events.html
> +                Introduction topode.js and JavaScript
typo: topode --> to Node

2018-10-08 08:26 UTC, minaorangina commented on events.html
> +              <a target="_bpnk" class="grey-text" href="https://nodegirls.typeform.com/to/wkVUzc">
_bpnk --> _blank

2018-10-08 19:24 UTC, BNewing commented
Sorry about that! Have committed fixing those :)

2018-10-30 16:58 UTC, minaorangina approved these changes

2018-10-30 16:59 UTC, merged