updates index page with next event
node-girls/node-girls-website pull request #70
Opened 2017-03-29 22:48 UTC by minaorangina

2017-03-29 22:51 UTC, claireinez requested changes

2017-03-29 22:51 UTC, claireinez commented on index.html
> +              <a href="https://twitter.com/nofootnotes">
I'm claireinez now on Twitter too :)

2017-03-30 10:11 UTC, minaorangina commented on index.html
> +              <a href="https://twitter.com/nofootnotes">
@claireinez Updated it now!

2017-03-30 15:44 UTC, claireinez approved these changes

2017-03-30 15:44 UTC, claireinez commented
Haaaa you had to update it in so many places! Thanks @minaorangina!

2017-03-30 16:25 UTC, merged